preprocess:
  input_files:
    - names:
        - scratch/scraped_posts.csv
      kind: csv
    - names:
        - scratch/test_set_articles.ZIP
      kind: zip
  steps:
    - kind: account-masker
    - kind: stopword-remover
    - kind: punctuation-remover
    - kind: lemmatizer
#  - kind: stemmer
